### ISSUE TITLE
Execve launched when trying to set variable without export

### ISSUE THREAD

**Issue by Ala-Na** [lucocozz/minishell#75]
Obtained :
![image](https://user-images.githubusercontent.com/67599180/137602507-a1b7a0a7-4377-479c-a737-d8458644d3dd.png)

Expected :
![image](https://user-images.githubusercontent.com/67599180/137602519-1c7b3fe5-d038-408e-a376-f5b556ca3bba.png)

EDIT :
Issue is meeted even when variable is set with a value.

Maybe it's a matter of subject interpretation ? (not taking care of non exported values)

**Comment by rotrojan** [comment]
Posix shells use two type of variables : _shell variables_ and _environment variables_.
- _Environment variables_ are part of the environment and all new instances of a shell called from the present shell will inherit those variables. They can be added to the environment via `export` and displayed with `env`.
- _Shell variables_ are specifics to the present instance of the shell. They can be added with `set` and displayed with `set` or `declare`. Another way to add those variables is by simply typing `var_name=var_value`. If `export` is  not explicitly invoked, the variables will be consider as a _shell variable_ and not as an _environment variable_.
The subject of minishell asks only to deal with `export` and _environment variables_. _Shell variables_ are beyond the scope of the subject and therefore are not meant to be handled by the project.
